services:
  agi-modelcard-postgres:
    container_name: agi-modelcard-postgres
    build: 
      context: ../../modelcard
      dockerfile: docker/postgres/Dockerfile.postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ../../modelcard/data/postgres_data:/var/lib/postgresql/data

  # agi-modelcard-redis:
  #   container_name: modelcard-redis
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  agi-modelcard-backend:
    container_name: agi-modelcard-backend
    build:
      context: ../../modelcard
      dockerfile: docker/backend/Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - agi-modelcard-postgres
      #- redis
    volumes:
      - ../../modelcard/modelcard-backend:/src

  agi-modelcard-frontend:
    container_name: agi-modelcard-frontend
    build:
      context: ../../modelcard
      dockerfile: docker/frontend/Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://${HOST}:${BACKEND_PORT}
    depends_on:
      - agi-modelcard-backend
    volumes:
      - ../../modelcard/modelcard-frontend:/app
      - /app/node_modules




      